image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - usr/bin/
    - /var/cache/apk/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - lint
  - test
  - build
  - publish

lint:
  tags:
    - docker
  stage: lint
  script: "npm run lint"


test:
  tags:
    - docker
  stage: test
  script: "apk add chromium && CHROME_BIN=/usr/bin/chromium-browser npm run test -- --singleRun true"
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days

build:
  tags:
    - docker
  stage: build
  script: "npm run build"

publish:
  tags:
    - shell
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $DOCKER_REGISTRY_PASS | docker login --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build . --pull -f docker/build/Dockerfile -t "glacs22/main-cesium:$CI_COMMIT_SHORT_SHA" -t "glacs22/main-cesium:latest"
    - docker push "glacs22/main-cesium" --all-tags
  only:
    - master
